(() => {
  "use strict";

  const BLOCKED_CLASS = "ytai-blocked";
  const LOG_KEY = "ytai-blocked-log";
  const LOG_MAX = 500;

  const CONTAINER_SELECTORS = [
    "ytd-rich-item-renderer",
    "ytd-video-renderer",
    "ytd-compact-video-renderer",
    "ytd-grid-video-renderer",
    "ytd-reel-item-renderer",
    "yt-lockup-view-model",
  ].join(",");

  const BADGE_SELECTORS = ".ytBadgeShapeText, .badge-shape-wiz__text";

  const LABEL_RE =
    /altered or synthetic|altered content|synthetic content|made with ai|ai-generated|generated by ai|altered or fully generated/i;

  const WATCH_DATA_RE = /howThisWasMadeSectionViewModel|made with AI/;

  // ---------- log ----------

  function loadLog() {
    try {
      return JSON.parse(localStorage.getItem(LOG_KEY)) || [];
    } catch {
      return [];
    }
  }

  function saveLog(entries) {
    localStorage.setItem(LOG_KEY, JSON.stringify(entries));
  }

  function videoIdFromUrl(url) {
    try {
      const u = new URL(url, location.origin);
      if (u.pathname === "/watch") return u.searchParams.get("v");
      const shorts = u.pathname.match(/^\/shorts\/([\w-]+)/);
      if (shorts) return shorts[1];
      return null;
    } catch {
      return null;
    }
  }

  function extractInfo(container) {
    const anchor =
      container.querySelector('a[href*="/watch?v="]') ||
      container.querySelector('a[href^="/shorts/"]');
    if (!anchor) return null;
    const url = new URL(anchor.getAttribute("href"), location.origin).toString();
    const id = videoIdFromUrl(url);
    if (!id) return null;
    const title =
      (anchor.getAttribute("title") || "").trim() ||
      container.querySelector("#video-title, h3, .yt-lockup-metadata-view-model__heading")?.textContent.trim() ||
      "(untitled)";
    return { id, url, title };
  }

  function logBlocked(info) {
    const entries = loadLog();
    if (entries.some((e) => e.id === info.id)) return;
    entries.unshift({ ...info, time: Date.now() });
    saveLog(entries.slice(0, LOG_MAX));
    updatePanel();
  }

  // ---------- panel ----------

  let panel = null;
  let listEl = null;
  let countEl = null;
  let visible = false;

  function buildPanel() {
    panel = document.createElement("div");
    panel.id = "ytai-panel";
    const btn = document.createElement("button");
    btn.id = "ytai-toggle";
    btn.title = "Blocked AI videos";
    countEl = document.createElement("span");
    countEl.id = "ytai-count";
    btn.appendChild(countEl);

    const box = document.createElement("div");
    box.id = "ytai-box";
    box.style.display = "none";

    const header = document.createElement("div");
    header.id = "ytai-header";
    const title = document.createElement("strong");
    title.textContent = "Blocked AI videos";
    const actions = document.createElement("div");
    const copyBtn = document.createElement("button");
    copyBtn.textContent = "Copy URLs";
    copyBtn.addEventListener("click", copyAll);
    const clearBtn = document.createElement("button");
    clearBtn.textContent = "Clear";
    clearBtn.addEventListener("click", clearLog);
    actions.append(copyBtn, clearBtn);
    header.append(title, actions);

    listEl = document.createElement("div");
    listEl.id = "ytai-list";

    box.append(header, listEl);
    panel.append(btn, box);
    document.documentElement.appendChild(panel);

    btn.addEventListener("click", () => {
      visible = !visible;
      box.style.display = visible ? "flex" : "none";
      if (visible) renderList();
    });
  }

  function renderList() {
    const entries = loadLog();
    listEl.replaceChildren();
    if (entries.length === 0) {
      const empty = document.createElement("div");
      empty.className = "ytai-empty";
      empty.textContent = "Nothing blocked yet.";
      listEl.appendChild(empty);
      return;
    }
    for (const entry of entries) {
      const a = document.createElement("a");
      a.href = entry.url;
      a.textContent = entry.title;
      a.target = "_blank";
      const row = document.createElement("div");
      row.className = "ytai-row";
      row.appendChild(a);
      listEl.appendChild(row);
    }
  }

  function updatePanel() {
    if (!countEl) return;
    const n = loadLog().length;
    countEl.textContent = n > 0 ? String(n) : "";
  }

  function copyAll() {
    const urls = loadLog().map((e) => e.url).join("\n");
    navigator.clipboard.writeText(urls).catch(() => {});
  }

  function clearLog() {
    saveLog([]);
    updatePanel();
    renderList();
  }

  // ---------- watch page blocking ----------

  const bypassed = new Set();
  let watchInFlight = false;
  let keepPausedTimer = null;

  function watchTitle() {
    const h1 = document.querySelector("h1.ytd-watch-metadata yt-formatted-string, h1.title");
    const t = h1?.textContent?.trim() || document.title.replace(/ - YouTube$/, "");
    return t || "(untitled)";
  }

  function blockWatchPage(id) {
    if (document.getElementById("ytai-overlay")) return;
    logBlocked({ id, url: `https://www.youtube.com/watch?v=${id}`, title: watchTitle() });
    showWatchOverlay(id);
  }

  function showWatchOverlay(id) {
    pauseMedia();

    const overlay = document.createElement("div");
    overlay.id = "ytai-overlay";

    const card = document.createElement("div");
    card.id = "ytai-overlay-card";
    const heading = document.createElement("strong");
    heading.textContent = "AI-labeled video blocked";
    const msg = document.createElement("div");
    msg.textContent = "YouTube labels this content as altered or synthetic. Logged to your blocked list.";
    const buttons = document.createElement("div");

    const watchBtn = document.createElement("button");
    watchBtn.textContent = "Watch anyway";
    watchBtn.addEventListener("click", () => {
      bypassed.add(id);
      removeOverlay();
    });

    const backBtn = document.createElement("button");
    backBtn.textContent = "Go back";
    backBtn.addEventListener("click", () => {
      removeOverlay();
      if (history.length > 1) history.back();
      else location.assign("https://www.youtube.com/");
    });

    buttons.append(watchBtn, backBtn);
    card.append(heading, msg, buttons);
    overlay.appendChild(card);
    document.documentElement.appendChild(overlay);

    keepPausedTimer = setInterval(() => {
      if (!document.getElementById("ytai-overlay")) {
        clearInterval(keepPausedTimer);
        return;
      }
      pauseMedia();
    }, 800);
  }

  function removeOverlay() {
    document.getElementById("ytai-overlay")?.remove();
    if (keepPausedTimer) {
      clearInterval(keepPausedTimer);
      keepPausedTimer = null;
    }
  }

  function pauseMedia() {
    document.querySelectorAll("video, audio").forEach((m) => m.pause());
  }

  async function checkWatchPage() {
    if (!location.pathname.startsWith("/watch")) return;
    const id = currentVideoId();
    if (!id || bypassed.has(id) || watchInFlight) return;

    // Fast path: disclosure panel rendered in the DOM
    if (document.querySelector("how-this-was-made-section-view-model")) {
      blockWatchPage(id);
      return;
    }
    // "AI" badge next to the video title
    for (const badge of document.querySelectorAll(BADGE_SELECTORS)) {
      if (badge.textContent.trim().toUpperCase() === "AI") {
        blockWatchPage(id);
        return;
      }
    }

    // Fallback: the disclosure usually lives only in the page's embedded
    // JSON, so fetch the watch page and search the HTML.
    watchInFlight = true;
    try {
      const res = await fetch(location.href, { credentials: "include" });
      const html = await res.text();
      if (WATCH_DATA_RE.test(html) && !bypassed.has(id)) {
        blockWatchPage(id);
      }
    } catch {
      // network failure: do nothing
    } finally {
      watchInFlight = false;
    }
  }

  function currentVideoId() {
    return videoIdFromUrl(location.href);
  }

  // ---------- card blocking ----------

  function injectStyle() {
    const style = document.createElement("style");
    style.textContent = `
.${BLOCKED_CLASS}{display:none !important;}
#ytai-panel{position:fixed;bottom:16px;right:16px;z-index:999999;font-family:sans-serif;}
#ytai-toggle{width:36px;height:36px;border-radius:50%;border:1px solid #606060;background:#0f0f0f;color:#fff;cursor:pointer;position:relative;font-size:16px;}
#ytai-toggle::after{content:"AI";}
#ytai-count{position:absolute;top:-6px;right:-6px;background:#c00;color:#fff;border-radius:9px;font-size:10px;min-width:16px;height:16px;line-height:16px;text-align:center;}
#ytai-box{position:absolute;bottom:44px;right:0;width:340px;max-height:420px;display:none;flex-direction:column;background:#0f0f0f;border:1px solid #606060;border-radius:8px;color:#f1f1f1;box-shadow:0 4px 16px rgba(0,0,0,.5);}
#ytai-header{display:flex;justify-content:space-between;align-items:center;padding:8px 10px;border-bottom:1px solid #303030;}
#ytai-header button{background:#272727;color:#f1f1f1;border:none;border-radius:4px;padding:3px 8px;margin-left:6px;cursor:pointer;font-size:11px;}
#ytai-header button:hover{background:#3f3f3f;}
#ytai-list{overflow-y:auto;padding:6px 10px;}
.ytai-row{padding:5px 0;border-bottom:1px solid #1f1f1f;font-size:12px;}
.ytai-row a{color:#3ea6ff;text-decoration:none;word-break:break-word;}
.ytai-empty{padding:10px;color:#aaa;font-size:12px;}
#ytai-overlay{position:fixed;inset:0;z-index:999998;background:rgba(0,0,0,.85);display:flex;align-items:center;justify-content:center;font-family:sans-serif;}
#ytai-overlay-card{background:#0f0f0f;border:1px solid #606060;border-radius:8px;padding:24px;max-width:420px;color:#f1f1f1;text-align:center;}
#ytai-overlay-card strong{font-size:18px;display:block;margin-bottom:8px;}
#ytai-overlay-card > div:not(:last-of-type){margin-bottom:8px;}
#ytai-overlay-card button{background:#272727;color:#f1f1f1;border:1px solid #606060;border-radius:18px;padding:8px 18px;margin:0 6px;cursor:pointer;font-size:13px;}
#ytai-overlay-card button:hover{background:#3f3f3f;}
`;
    document.documentElement.appendChild(style);
  }

  function isAiLabeled(container) {
    if (container.querySelector("how-this-was-made-section-view-model")) {
      return true;
    }
    for (const badge of container.querySelectorAll(BADGE_SELECTORS)) {
      const text = badge.textContent.trim();
      if (text.toUpperCase() === "AI" || LABEL_RE.test(text)) {
        return true;
      }
    }
    return false;
  }

  function scan(root) {
    for (const container of (root || document).querySelectorAll(CONTAINER_SELECTORS)) {
      if (container.classList.contains(BLOCKED_CLASS)) continue;
      if (isAiLabeled(container)) {
        container.classList.add(BLOCKED_CLASS);
        const info = extractInfo(container);
        if (info) logBlocked(info);
      }
    }
  }

  let scheduled = false;
  function scheduleScan() {
    if (scheduled) return;
    scheduled = true;
    setTimeout(() => {
      scheduled = false;
      scan();
    }, 150);
  }

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.addedNodes.length > 0) {
        scheduleScan();
        return;
      }
    }
  });

  function start() {
    injectStyle();
    buildPanel();
    updatePanel();
    scan();
    checkWatchPage();
    observer.observe(document.body, { childList: true, subtree: true });
  }

  window.addEventListener("yt-navigate-finish", () => {
    removeOverlay();
    scan();
    setTimeout(checkWatchPage, 200);
  });

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
})();
